# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Flashcards' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flashcards
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'TextFieldEffects'

  target 'FlashcardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashcardsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
